In [1]:
import pickle
import numpy as np
import pandas as pd
import re

In [10]:
%system free -m

['               total        used        free      shared  buff/cache   available',
 'Mem:          256630      121245      131001         882        4382      133053',
 'Swap:              0           0           0']

In [3]:
geno = pd.read_pickle("gene_pav_pfam.pkl")

NameError: name 'pd' is not defined

In [13]:
geno.head()

,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Pfam_domain
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF02776
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF10551
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF03101
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434

In [2]:
# Processing Pfam dataset

In [3]:
#Load file
gene_pav = pd.read_csv('../genotype/soybean_pan_pav.matrix_gene.txt', sep='\t', header=None, engine='c', low_memory=False)

In [4]:
gene_pav.head()

,0,1,2,3,4,5,6,7,8,9,...,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110
0,Individual,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,...,USB-025,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046
1,GlymaLee.01G000100.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,GlymaLee.01G000200.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,GlymaLee.01G000300.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,GlymaLee.01G000400.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [5]:
gene_pav.columns = gene_pav.iloc[0]  # set first row as columns
gene_pav = gene_pav[1:]

In [6]:
gene_pav.head()

,Individual,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,...,USB-025,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046
1,GlymaLee.01G000100.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,GlymaLee.01G000200.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,GlymaLee.01G000300.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,GlymaLee.01G000400.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
5,GlymaLee.01G000500.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [7]:
gene_pav.set_index(gene_pav.columns[0], inplace=True)
gene_pav.index.name = "Gene_ID"

In [8]:
gene_pav.head()

,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-025,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046
Gene_ID,,,,,,,,,,,,,,,,,,,,,
GlymaLee.01G000100.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GlymaLee.01G000200.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GlymaLee.01G000300.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GlymaLee.01G000400.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GlymaLee.01G000500.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [9]:
#Load map
map_id = pd.read_csv('../genotype/gene_protein_map1.txt', sep=" ", header=None)

In [10]:
map_id.head()

                        0                          1
0              Protein_ID                    Gene_ID
1  GlymaLee.01G057700.1.p  GlymaLee.01G057700.1.v1.1
2  GlymaLee.01G146700.1.p  GlymaLee.01G146700.1.v1.1
3  GlymaLee.01G202400.1.p  GlymaLee.01G202400.1.v1.1
4  GlymaLee.01G180600.1.p  GlymaLee.01G180600.1.v1.1

In [11]:
map_id.columns = map_id.iloc[0]  # set first row as columns
map_id = map_id[1:]   
map_id = map_id.set_index("Gene_ID")

In [12]:
map_id.head()

0                                      Protein_ID
Gene_ID
GlymaLee.01G057700.1.v1.1  GlymaLee.01G057700.1.p
GlymaLee.01G146700.1.v1.1  GlymaLee.01G146700.1.p
GlymaLee.01G202400.1.v1.1  GlymaLee.01G202400.1.p
GlymaLee.01G180600.1.v1.1  GlymaLee.01G180600.1.p
GlymaLee.01G189700.1.v1.1  GlymaLee.01G189700.1.p

In [16]:
#Load pfam
pfam = pd.read_csv('../interproscan/gene_pfam_eval5.txt', sep="\t", header=None)

In [17]:
pfam.head()

                        0            1
0              Protein_ID  Pfam_domain
1  GlymaLee.01G000400.1.p      PF02776
2  GlymaLee.01G000700.1.p      PF04434
3  GlymaLee.01G000700.1.p      PF10551
4  GlymaLee.01G000800.1.p      PF03101

In [18]:
pfam.columns = pfam.iloc[0]  # set first row as columns
pfam = pfam[1:]   
pfam = pfam.set_index("Protein_ID")

In [19]:
pfam.head()

0                      Pfam_domain
Protein_ID
GlymaLee.01G000400.1.p     PF02776
GlymaLee.01G000700.1.p     PF04434
GlymaLee.01G000700.1.p     PF10551
GlymaLee.01G000800.1.p     PF03101
GlymaLee.01G000800.1.p     PF04434

In [20]:
def extract_gene_id(protein_id):
    # match patterns like GlymaLee.U002300.1.p or UWASoyPan00005.t1
    m = re.search(r'([A-Za-z]*[U0-9]+[A-Za-z0-9]*)', protein_id)
    return m.group(1) if m else protein_id

    #its regex pattern search tries to find something that looks like a compact gene or protein ID, possibly starting with letters, followed by digits, followed by more alphanumeric characters
    #The first is telling first character could be letters or numbers or U and the string after '+' is telling it could be letters or numbers
    #giving U separately as I know some proteins start way

In [21]:
pfam["Protein_part"] = pfam.index.to_series().apply(extract_gene_id)

In [22]:
pfam["Pfam_protein"] = pfam["Pfam_domain"] + "_" + pfam["Protein_part"]
pfam = pfam.drop(columns=["Pfam_domain", "Protein_part"])

In [23]:
pfam.head()

0                            Pfam_protein
Protein_ID
GlymaLee.01G000400.1.p  PF02776_01G000400
GlymaLee.01G000700.1.p  PF04434_01G000700
GlymaLee.01G000700.1.p  PF10551_01G000700
GlymaLee.01G000800.1.p  PF03101_01G000800
GlymaLee.01G000800.1.p  PF04434_01G000800

In [24]:
pfam.to_csv("protein_pfam_map.csv", sep="\t")

In [25]:
# Merging

In [26]:
gene_pav.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51414 entries, GlymaLee.01G000100.1.v1.1 to UWASoyPan05315
Columns: 1110 entries, AB-01 to USB-046
dtypes: object(1110)
memory usage: 435.8+ MB

In [27]:
map_id.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51416 entries, GlymaLee.01G057700.1.v1.1 to UWASoyPan01261
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Protein_ID  51416 non-null  object
dtypes: object(1)
memory usage: 803.4+ KB

In [28]:
gene_pav_map = pd.merge(gene_pav, map_id, on='Gene_ID', how='inner', indicator=False)

In [29]:
gene_pav_map.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51416 entries, GlymaLee.01G000100.1.v1.1 to UWASoyPan05315
Columns: 1111 entries, AB-01 to Protein_ID
dtypes: object(1111)
memory usage: 436.2+ MB

In [30]:
gene_pav_map.head()

,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Protein_ID
Gene_ID,,,,,,,,,,,,,,,,,,,,,
GlymaLee.01G000100.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,GlymaLee.01G000100.1.p
GlymaLee.01G000200.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,GlymaLee.01G000200.1.p
GlymaLee.01G000300.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,GlymaLee.01G000300.1.p
GlymaLee.01G000400.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,GlymaLee.01G000400.1.p
GlymaLee.01G000500.1.v1.1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,GlymaLee.01G000500.1.p

In [31]:
pfam.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53721 entries, GlymaLee.01G000400.1.p to UWASoyPan05315.t1
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pfam_protein  53721 non-null  object
dtypes: object(1)
memory usage: 839.4+ KB

In [32]:
gene_pav_pfam = pd.merge(gene_pav_map, pfam, on='Protein_ID', how='right', indicator=False)

In [33]:
gene_pav_pfam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53721 entries, 0 to 53720
Columns: 1112 entries, AB-01 to Pfam_protein
dtypes: object(1112)
memory usage: 455.8+ MB

In [34]:
gene_pav_pfam.head()

,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Protein_ID,Pfam_protein
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,GlymaLee.01G000400.1.p,PF02776_01G000400
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,GlymaLee.01G000700.1.p,PF04434_01G000700
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,GlymaLee.01G000700.1.p,PF10551_01G000700
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,GlymaLee.01G000800.1.p,PF03101_01G000800
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,GlymaLee.01G000800.1.p,PF04434_01G000800

In [35]:
nan_values = gene_pav_pfam[gene_pav_pfam.isna().any(axis=1)]

In [36]:
nan_values.head()

Empty DataFrame
Columns: [AB-01, AB-02, BR-01, BR-02, BR-03, BR-04, BR-05, BR-06, BR-07, BR-08, BR-09, BR-10, BR-11, BR-12, BR-13, BR-14, BR-15, BR-16, BR-17, BR-18, BR-20, BR-23, BR-24, BR-29, BR-30, BR-32, DT2000, ESS, For, HN001, HN002, HN003, HN004, HN005, HN006, HN007, HN008, HN009, HN010, HN011, HN012, HN013, HN015, HN016B, HN017B, HN018, HN019, HN021, HN022, HN023, HN024, HN025, HN026, HN027, HN028, HN029, HN030, HN031, HN032, HN033, HN034, HN035, HN036, HN037, HN038, HN039, HN040, HN041, HN042, HN043, HN044, HN045, HN046, HN047, HN048, HN049, HN050, HN051, HN052, HN053, HN054, HN055, HN056, HN057, HN058, HN059, HN060, HN061, HN062, HN063, HN064, HN065, HN066, HN067, HN068, HN069, HN070, HN071, HN072, HN073, ...]
Index: []

[0 rows x 1112 columns]

In [37]:
nan_values.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Columns: 1112 entries, AB-01 to Pfam_protein
dtypes: object(1112)
memory usage: 0.0+ bytes

In [38]:
gene_pav_pfam = gene_pav_pfam.drop(["Protein_ID"], axis=1)

In [39]:
gene_pav_pfam.head()

,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Pfam_protein
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF02776_01G000400
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434_01G000700
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF10551_01G000700
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF03101_01G000800
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434_01G000800

In [40]:
gene_pav_pfam.to_csv("pfam_pav_clean.tsv", sep="\t")

In [41]:
df = pd.read_csv("pfam_pav_clean.tsv", sep="\t", header=None, low_memory=False)

In [42]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111
0,NaN,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,...,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Pfam_protein
1,0.0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF02776_01G000400
2,1.0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434_01G000700
3,2.0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF10551_01G000700
4,3.0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF03101_01G000800

In [43]:
df = df.iloc[:, 1:]

In [44]:
df.head()

,1,2,3,4,5,6,7,8,9,10,...,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111
0,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,BR-08,...,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046,Pfam_protein
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF02776_01G000400
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF04434_01G000700
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF10551_01G000700
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,PF03101_01G000800

In [45]:
df_t = df.transpose()

In [46]:
df_t.head()

,0,1,2,3,4,5,6,7,8,9,...,53712,53713,53714,53715,53716,53717,53718,53719,53720,53721
1,AB-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
2,AB-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
3,BR-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
4,BR-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
5,BR-03,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [47]:
#Load pfam
#pfam = pd.read_csv('../interproscan/pfam_domain_names.txt', sep="\t", header=None)

In [48]:
df_t.set_index(df_t.columns[0], inplace=True)
df_t.index.name = "Data-storage-ID"

In [49]:
df_t.head()

,1,2,3,4,5,6,7,8,9,10,...,53712,53713,53714,53715,53716,53717,53718,53719,53720,53721
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [50]:
df_t.tail()

,1,2,3,4,5,6,7,8,9,10,...,53712,53713,53714,53715,53716,53717,53718,53719,53720,53721
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
USB-042,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0
USB-043,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
USB-045,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
USB-046,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
Pfam_protein,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315

In [51]:
df_t.columns = df_t.iloc[-1]   # set last row as column names
df_t = df_t[:-1]               # drop the last row since it's now the header

In [52]:
df_t.head()

Pfam_protein,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [53]:
df_t.index.name = "Data-storage-ID"

In [54]:
df_t.head()

Pfam_protein,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [55]:
df_t.to_csv("df.csv", sep="\t")

In [56]:
df = pd.read_csv("df.csv", sep="\t", header=None, low_memory=False)

In [57]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,53712,53713,53714,53715,53716,53717,53718,53719,53720,53721
0,Data-storage-ID,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
1,AB-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
2,AB-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
3,BR-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
4,BR-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0

In [58]:
df.columns = df.iloc[0]  # set first row as columns
df = df[1:]

In [59]:
df.head()

,Data-storage-ID,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
1,AB-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
2,AB-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
3,BR-01,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
4,BR-02,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
5,BR-03,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [60]:
df = df.set_index("Data-storage-ID")

In [61]:
df.head()

,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1110 entries, AB-01 to USB-046
Columns: 53721 entries, PF02776_01G000400 to PF02427_UWASoyPan05315
dtypes: object(53721)
memory usage: 455.0+ MB

In [63]:
df = df.astype(int)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1110 entries, AB-01 to USB-046
Columns: 53721 entries, PF02776_01G000400 to PF02427_UWASoyPan05315
dtypes: int64(53721)
memory usage: 455.0+ MB

In [107]:
df = df.groupby(df.columns, axis=1).sum()

/tmp/ipykernel_3686471/3829782958.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df = df.groupby(df.columns, axis=1).sum()

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1110 entries, AB-01 to USB-046
Columns: 56661 entries, PF00004_01G136900 to PF20160_UWASoyPan03185
dtypes: int64(56661)
memory usage: 479.8+ MB

In [65]:
df.head()

,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0

In [66]:
df.to_pickle("pfam_pav_newIDs_eval5.pkl")

In [67]:
from sklearn.feature_selection import VarianceThreshold

In [68]:
selector = VarianceThreshold(threshold=0.01)

In [69]:
df_high_variance = selector.fit_transform(df)

In [70]:
df_high_variance.shape

(1110, 1196)

In [71]:
selected_features_mask = selector.get_support()

In [72]:
selected_feature_names = df.columns[selected_features_mask]

In [73]:
df_selected = pd.DataFrame(df_high_variance, columns=selected_feature_names, index=df.index)

In [74]:
df_selected.head()

,PF00931_01G030900,PF20160_01G030900,PF00332_01G044800,PF00195_01G074000,PF02797_01G074000,PF13041_01G086700,PF05056_01G086800,PF00931_01G088400,PF01582_01G088400,PF01086_01G090700,...,PF00069_UWASoyPan05055,PF07651_UWASoyPan05083,PF01541_UWASoyPan05113,PF07014_UWASoyPan05162,PF03140_UWASoyPan05171,PF06026_UWASoyPan05196,PF00232_UWASoyPan05231,PF07651_UWASoyPan05301,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,1,1,0,0
AB-02,0,0,1,1,1,1,1,1,1,1,...,0,1,0,1,0,0,1,1,0,1
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,1,0,1,0,0,1,1,0,1
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,1,0,1,0,0,1,1,0,1
BR-03,1,1,1,1,1,0,0,1,1,1,...,0,1,0,1,0,0,1,1,0,0

In [75]:
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1110 entries, AB-01 to USB-046
Columns: 1196 entries, PF00931_01G030900 to PF00931_UWASoyPan05312
dtypes: int64(1196)
memory usage: 10.1+ MB

In [76]:
df_selected.to_pickle("pfam_pav_newIDs_eval5_afterFS.pkl")