In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import pickle

In [19]:
pheno = pd.read_csv ('yield_pheno.txt', sep = '\t')

In [20]:
pheno.head()

   observation_value                   method_name Data-storage-ID
0               0.08      SOYBEAN.EVALUATION.MS989         USB-756
1               0.09     SOYBEAN.EVALUATION.MN0102         USB-014
2               0.14  SOYBEAN.EVALUATION.MS2000_02         USB-035
3               0.15      SOYBEAN.EVALUATION.MS923         USB-499
4               0.15     SOYBEAN.EVALUATION.MN0102         USB-393

In [21]:
pheno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   observation_value  893 non-null    float64
 1   method_name        893 non-null    object
 2   Data-storage-ID    893 non-null    object
dtypes: float64(1), object(2)
memory usage: 21.1+ KB

In [23]:
pheno['new_line'] = pheno['Data-storage-ID'] + '_' + pheno['method_name']

In [25]:
pheno.head()

,observation_value,method_name,Data-storage-ID,new_line
0,0.08,SOYBEAN.EVALUATION.MS989,USB-756,USB-756_SOYBEAN.EVALUATION.MS989
1,0.09,SOYBEAN.EVALUATION.MN0102,USB-014,USB-014_SOYBEAN.EVALUATION.MN0102
2,0.14,SOYBEAN.EVALUATION.MS2000_02,USB-035,USB-035_SOYBEAN.EVALUATION.MS2000_02
3,0.15,SOYBEAN.EVALUATION.MS923,USB-499,USB-499_SOYBEAN.EVALUATION.MS923
4,0.15,SOYBEAN.EVALUATION.MN0102,USB-393,USB-393_SOYBEAN.EVALUATION.MN0102

In [29]:
pheno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   observation_value  893 non-null    float64
 1   method_name        893 non-null    object
 2   Data-storage-ID    893 non-null    object
 3   new_line           893 non-null    object
dtypes: float64(1), object(3)
memory usage: 28.0+ KB

In [30]:
# Extract the specified column
column_data = pheno[['method_name']]

# Initialize OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)  # Drop first category to avoid multicollinearity

# Fit and transform the OneHotEncoder
one_hot_encoded = ohe.fit_transform(column_data)

In [57]:
# Get the column names after one-hot encoding
categories = ohe.get_feature_names_out(['method_name'])
#the category name i as followed - Location_year_BeiJing_2013. 
#So split based on underscores and pull the 2-4 parts to used as column names

feature_names = ['_'.join(col.split('_')[2:5]) for col in categories]

In [58]:
# Create a DataFrame with the one-hot encoded columns
one_hot_df = pd.DataFrame(one_hot_encoded, columns=feature_names)

In [59]:
#Check if ohe is done right
one_hot_df.head()

,SOYBEAN.EVALUATION.1IL64,SOYBEAN.EVALUATION.1IL66,SOYBEAN.EVALUATION.1MN63,SOYBEAN.EVALUATION.2IL81.1,SOYBEAN.EVALUATION.2IL81.2,SOYBEAN.EVALUATION.2KY81,SOYBEAN.EVALUATION.2MN81,SOYBEAN.EVALUATION.3IL83.1,SOYBEAN.EVALUATION.3IL83.2,SOYBEAN.EVALUATION.3IL84,...,SOYBEAN.EVALUATION.MN945,SOYBEAN.EVALUATION.MS1999_01,SOYBEAN.EVALUATION.MS2000_02,SOYBEAN.EVALUATION.MS2001_02,SOYBEAN.EVALUATION.MS2001_03,SOYBEAN.EVALUATION.MS2011_12,SOYBEAN.EVALUATION.MS923,SOYBEAN.EVALUATION.MS945,SOYBEAN.EVALUATION.MS967,SOYBEAN.EVALUATION.MS989
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
df = one_hot_df.astype(int)

print(df)

     SOYBEAN.EVALUATION.1IL64  SOYBEAN.EVALUATION.1IL66  \
0                           0                         0
1                           0                         0
2                           0                         0
3                           0                         0
4                           0                         0
..                        ...                       ...
888                         0                         0
889                         0                         0
890                         0                         0
891                         0                         0
892                         0                         0

     SOYBEAN.EVALUATION.1MN63  SOYBEAN.EVALUATION.2IL81.1  \
0                           0                           0
1                           0                           0
2                           0                           0
3                           0                           0
4                           0                           0
..                        ...                         ...
888                         0                           0
889                         0                           0
890                         0                           0
891                         0                           0
892                         0                           0

     SOYBEAN.EVALUATION.2IL81.2  SOYBEAN.EVALUATION.2KY81  \
0                             0                         0
1                             0                         0
2                             0                         0
3                             0                         0
4                             0                         0
..                          ...                       ...
888                           0                         0
889                           0                         0
890                           0                         0
891                           0                         0
892                           0                         0

     SOYBEAN.EVALUATION.2MN81  SOYBEAN.EVALUATION.3IL83.1  \
0                           0                           0
1                           0                           0
2                           0                           0
3                           0                           0
4                           0                           0
..                        ...                         ...
888                         0                           0
889                         0                           0
890                         0                           0
891                         0                           0
892                         0                           0

     SOYBEAN.EVALUATION.3IL83.2  SOYBEAN.EVALUATION.3IL84  ...  \
0                             0                         0  ...
1                             0                         0  ...
2                             0                         0  ...
3                             0                         0  ...
4                             0                         0  ...
..                          ...                       ...  ...
888                           0                         0  ...
889                           0                         0  ...
890                           0                         0  ...
891                           0                         0  ...
892                           0                         0  ...

     SOYBEAN.EVALUATION.MN945  SOYBEAN.EVALUATION.MS1999_01  \
0                           0                             0
1                           0                             0
2                           0                             0
3                           0                             0
4                           0                             0
..                        ...                           ...
888                         0                             0
889                         0                             0
890                         0                             0
891                         0                             0
892                         0                             0

     SOYBEAN.EVALUATION.MS2000_02  SOYBEAN.EVALUATION.MS2001_02  \
0                               0                             0
1                               0                             0
2                               1                             0
3                               0                             0
4                               0                             0
..                            ...                           ...
888                             0                             0
889                             0                             0
890                             0                             0
891                             0                             0
892                             0                             0

     SOYBEAN.EVALUATION.MS2001_03  SOYBEAN.EVALUATION.MS2011_12  \
0                               0                             0
1                               0                             0
2                               0                             0
3                               0                             0
4                               0                             0
..                            ...                           ...
888                             0                             1
889                             0                             1
890                             1                             0
891                             0                             1
892                             0                             1

     SOYBEAN.EVALUATION.MS923  SOYBEAN.EVALUATION.MS945  \
0                           0                         0
1                           0                         0
2                           0                         0
3                           1                         0
4                           0                         0
..                        ...                       ...
888                         0                         0
889                         0                         0
890                         0                         0
891                         0                         0
892                         0                         0

     SOYBEAN.EVALUATION.MS967  SOYBEAN.EVALUATION.MS989
0                           0                         1
1                           0                         0
2                           0                         0
3                           0                         0
4                           0                         0
..                        ...                       ...
888                         0                         0
889                         0                         0
890                         0                         0
891                         0                         0
892                         0                         0

[893 rows x 31 columns]

In [61]:
# Concatenate the one-hot encoded columns to the original DataFrame
ohe_data = pd.concat([pheno.reset_index(drop=True), df], axis=1)
ohe_data.head()

,observation_value,method_name,Data-storage-ID,new_line,SOYBEAN.EVALUATION.1IL64,SOYBEAN.EVALUATION.1IL66,SOYBEAN.EVALUATION.1MN63,SOYBEAN.EVALUATION.2IL81.1,SOYBEAN.EVALUATION.2IL81.2,SOYBEAN.EVALUATION.2KY81,...,SOYBEAN.EVALUATION.MN945,SOYBEAN.EVALUATION.MS1999_01,SOYBEAN.EVALUATION.MS2000_02,SOYBEAN.EVALUATION.MS2001_02,SOYBEAN.EVALUATION.MS2001_03,SOYBEAN.EVALUATION.MS2011_12,SOYBEAN.EVALUATION.MS923,SOYBEAN.EVALUATION.MS945,SOYBEAN.EVALUATION.MS967,SOYBEAN.EVALUATION.MS989
0,0.08,SOYBEAN.EVALUATION.MS989,USB-756,USB-756_SOYBEAN.EVALUATION.MS989,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0.09,SOYBEAN.EVALUATION.MN0102,USB-014,USB-014_SOYBEAN.EVALUATION.MN0102,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.14,SOYBEAN.EVALUATION.MS2000_02,USB-035,USB-035_SOYBEAN.EVALUATION.MS2000_02,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0.15,SOYBEAN.EVALUATION.MS923,USB-499,USB-499_SOYBEAN.EVALUATION.MS923,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0.15,SOYBEAN.EVALUATION.MN0102,USB-393,USB-393_SOYBEAN.EVALUATION.MN0102,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
# Drop the original 'Location_Year' column
ohe_data = ohe_data.drop(['method_name'], axis=1)

In [63]:
# Reorganize the columns to make 'PRT' the last column
column_order = [col for col in ohe_data.columns if col != 'observation_value'] + ['observation_value']
ohe_data = ohe_data[column_order]


# Display the result
ohe_data.head()

,Data-storage-ID,new_line,SOYBEAN.EVALUATION.1IL64,SOYBEAN.EVALUATION.1IL66,SOYBEAN.EVALUATION.1MN63,SOYBEAN.EVALUATION.2IL81.1,SOYBEAN.EVALUATION.2IL81.2,SOYBEAN.EVALUATION.2KY81,SOYBEAN.EVALUATION.2MN81,SOYBEAN.EVALUATION.3IL83.1,...,SOYBEAN.EVALUATION.MS1999_01,SOYBEAN.EVALUATION.MS2000_02,SOYBEAN.EVALUATION.MS2001_02,SOYBEAN.EVALUATION.MS2001_03,SOYBEAN.EVALUATION.MS2011_12,SOYBEAN.EVALUATION.MS923,SOYBEAN.EVALUATION.MS945,SOYBEAN.EVALUATION.MS967,SOYBEAN.EVALUATION.MS989,observation_value
0,USB-756,USB-756_SOYBEAN.EVALUATION.MS989,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.08
1,USB-014,USB-014_SOYBEAN.EVALUATION.MN0102,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.09
2,USB-035,USB-035_SOYBEAN.EVALUATION.MS2000_02,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.14
3,USB-499,USB-499_SOYBEAN.EVALUATION.MS923,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.15
4,USB-393,USB-393_SOYBEAN.EVALUATION.MN0102,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.15

In [64]:
ohe_data.to_pickle("phenotype_yield_data.pkl")